--- #YAML:1.0
name:               App-XUL
version:            0.03
abstract:           Perl extension for creating deployable platform-independent
author:
    - Tom Kirchner <tk@apple.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:         0
    Data::Dumper::Concise:  0
    Directory::Scratch::Structured:  0
    File::Copy::Recursive:  0
    IO::Socket:           0
    JSON:                 0
    LWP::Simple:          0
    Socket:               0
    Time::HiRes:          0
    URI::Escape:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
